version: "3.7"

services:
    database:
        image: postgres
        container_name: database
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB_PROD}
        volumes:
            - pgdata:/data/postgres
        networks: 
            - production

    database_test:
        image: postgres
        container_name: database_test
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB_TEST}
        networks: 
            - test

    app:
        build: .
        container_name: app
        command: sh -c "dockerize -wait tcp://database:5432 yarn dev"
        ports:
            - 3333:3333
        volumes: 
            - .:/home/root/api_test_gcb
        depends_on:
            - database
            - migrations
        networks: 
            - production

    app_test:
        build: .
        container_name: app_test
        command: bash -c "yarn test"
        volumes: 
            - .:/home/root/api_test_gcb
        depends_on:
            - database_test
        networks: 
            - test

    migrations:
        build: .
        container_name: migrations
        command: sh -c "dockerize -wait tcp://database:5432 yarn typeorm migration:run"
        depends_on: 
            - database
        networks: 
            - production

volumes:
    pgdata:
        driver: local

networks: 
    production:
        driver: bridge
    test:
        driver: bridge